### PR TITLE
Migrate Go client code to C#

### PR DESCRIPTION
**Pull request by toma3233**
### **User description**
Related to #12

This pull request migrates all Go code in the `api/v1/client` folder to C# as per the project's requirements.

- **Deletes Go files**: Removes the existing Go files `client_suite_test.go`, `client_test.go`, and `client.go` from the `api/v1/client` folder.
- **Adds C# files**: Introduces three new C# files to replace the deleted Go files. These are `client_suite_test.cs` for the test suite setup and teardown, `client_test.cs` for client tests, and `client.cs` which implements the client logic using gRPC.

---

For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/toma3233/mygreeterv3/issues/12?shareId=fee66174-e6ec-4fb2-af55-2bd476f1006c).

___

### **PR Type**
Enhancement, Tests

___

### **Description**
- Removed Go client implementation and tests.
- Added C# client implementation using gRPC.
- Added C# client suite setup and teardown using NUnit.
- Added C# client tests using NUnit.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>client.go</strong><dd><code>Remove Go client implementation.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

api/v1/client/client.go

- Deleted the Go client implementation file.

</details>

  </td>
  <td><a href="https://github.com/toma3233/mygreeterv3/pull/13/files#diff-c0847949469c7ac9deed091ae7fb9ad59ae5616e0c8985a6eb48bcf485bbc149">+0/-29</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>client.cs</strong><dd><code>Add C# client implementation.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

api/v1/client/client.cs

- Added C# client implementation using gRPC.

</details>

  </td>
  <td><a href="https://github.com/toma3233/mygreeterv3/pull/13/files#diff-1f2b6a1153cbd2220a37884dcbfbebb610d7d8ad2cfbcd3694bce7e279c7f6bb">+24/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>client_suite_test.go</strong><dd><code>Remove Go client suite test.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

api/v1/client/client_suite_test.go

- Deleted the Go client suite test file.

</details>

  </td>
  <td><a href="https://github.com/toma3233/mygreeterv3/pull/13/files#diff-11b5d94aee689f51be2b74625d6f39552b6925840f5de65829f7fcd0d6488125">+0/-13</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>client_test.go</strong><dd><code>Remove Go client tests.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

api/v1/client/client_test.go

- Deleted the Go client test file.

</details>

  </td>
  <td><a href="https://github.com/toma3233/mygreeterv3/pull/13/files#diff-18c67fef1962da3aeb3f8fe8754ff3cbf0615ca96cadc3c47c030fb018c07267">+0/-24</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>client_suite_test.cs</strong><dd><code>Add C# client suite setup and teardown.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

api/v1/client/client_suite_test.cs

- Added C# client suite setup and teardown using NUnit.

</details>

  </td>
  <td><a href="https://github.com/toma3233/mygreeterv3/pull/13/files#diff-43254744aa12e1352dd3dacebe8746fd2425be92b4c899df73583062d1d1d539">+20/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>client_test.cs</strong><dd><code>Add C# client tests.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

api/v1/client/client_test.cs

- Added C# client tests using NUnit.

</details>

  </td>
  <td><a href="https://github.com/toma3233/mygreeterv3/pull/13/files#diff-eb6c38bc3646edf2d54a5d8c6520f79289f46b54e6a5b4ea8e183fec730c5a3a">+25/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by toma3233** [comment]
@CodiumAI-Agent /review

**Comment by toma3233** [comment]
Preparing PR description...

**Comment by toma3233** [comment]
**[PR Description](https://github.com/toma3233/mygreeterv3/pull/13)** updated to latest commit (https://github.com/toma3233/mygreeterv3/commit/ba8d3258ea25dc66ff14cd8eb481ddcbcce983b3)

**Comment by toma3233** [comment]
Preparing review...

**Comment by toma3233** [comment]
**[Persistent review](https://github.com/toma3233/mygreeterv3/pull/13#issuecomment-2192272205)** updated to latest commit https://github.com/toma3233/mygreeterv3/commit/ba8d3258ea25dc66ff14cd8eb481ddcbcce983b3

**Comment by cmhamakawa** [comment]
Preparing review...

**Comment by cmhamakawa** [comment]
**[Persistent review](https://github.com/toma3233/mygreeterv3/pull/13#issuecomment-2192272205)** updated to latest commit https://github.com/toma3233/mygreeterv3/commit/ba8d3258ea25dc66ff14cd8eb481ddcbcce983b3

**Comment by cmhamakawa** [comment]
Preparing review...

**Comment by cmhamakawa** [comment]
**[Persistent review](https://github.com/toma3233/mygreeterv3/pull/13#issuecomment-2192272205)** updated to latest commit https://github.com/toma3233/mygreeterv3/commit/ba8d3258ea25dc66ff14cd8eb481ddcbcce983b3

**Comment by cmhamakawa** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by cmhamakawa** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Pull request closed without merging**
